language: ruby
script: bundle exec rake
bundler_args: --without=development --jobs=4
cache: bundler
sudo: false

before_script:
  - bin/setup

rvm:
  - '2.1.5'
  - '2.2.1'
  - '2.3.3'
  - '2.4.0'
  - 'ruby-head'
  - 'jruby-head'
  - 'rbx-3'

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 'ruby-head'
    - rvm: 'jruby-head'
    - rvm: 'rbx-3'

addons:
  code_climate:
    repo_token:
      secure: "M73JwMGXAtqe2xB+DE/Db+ZHFLRYX3oLY4qq2ZOvm6+EwwrVwHqE93TXN1YMqABcvAVLXo4FsELo1P6L3i+GwFNmtbFzUVQ1MMiPZffGwU85aEg6leix6jnnZdubWLePos0ldTve03pmsCiJ27ijnFG9gY6WQ8cOQEL6c8wikIE="
