language: ruby
cache: bundler

before_install:
  - gem install bundler rake

before_script:
  - bin/setup

after_success:
  - bundle exec codeclimate-test-reporter

rvm:
  - '2.3.1'
  - '2.3.3'
  - '2.4.0'
  - 'ruby-head'
  - 'jruby-head'
  - 'rbx-3'

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 'ruby-head'
    - rvm: 'jruby-head'
    - rvm: 'rbx-3'

addons:
  code_climate:
    repo_token:
      secure: "M73JwMGXAtqe2xB+DE/Db+ZHFLRYX3oLY4qq2ZOvm6+EwwrVwHqE93TXN1YMqABcvAVLXo4FsELo1P6L3i+GwFNmtbFzUVQ1MMiPZffGwU85aEg6leix6jnnZdubWLePos0ldTve03pmsCiJ27ijnFG9gY6WQ8cOQEL6c8wikIE="
