language: ruby
script: bundle exec rake
bundler_args: --without=development --jobs=4
cache: bundler

before_script:
  - bin/setup

rvm:
  - '2.0.0'
  - '2.1.2'
  - '2.1.5'
  - '2.2.0'
  - 'ruby-head'
  #- 'rbx-2.3.0'

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 'ruby-head'
