language: ruby
script: bundle exec rake
# Rubygems doesn't handle threading well: https://github.com/rubygems/rubygems/pull/1005
bundler_args: --without=development #--jobs=4
cache: bundler
before_script:
  - createuser -U postgres -s nvst
  - bin/setup
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.4
  - rbx-2.3.0
