default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV['FENGB_NVST_DB_POOL'] %>
  host:     <%= ENV['FENGB_NVST_DB_HOST'] %>
  port:     <%= ENV['FENGB_NVST_DB_PORT'] %>
  database: <%= ENV['FENGB_NVST_DB_NAME'] %>
  username: <%= ENV['FENGB_NVST_DB_USER'] %>
  password: <%= ENV['FENGB_NVST_DB_PASS'] %>

development: *default
test:        *default
production:  *default
